In [17]:
# Uploading necessary packages
import numpy as np
import pandas as pd
import bokeh
from bokeh.plotting import figure

In [28]:
# Uploading data sets
df_2017 = pd.read_excel('D:\Disinfromation project\kwb-2017.xls')
df_2016 = pd.read_excel('D:\Disinfromation Project\kwb-2016.xls')

In [29]:
# Slicing data set by a municipalities (by specific criterion in column)
df_muni = df_2017.loc[df_2017['type_of_area'] == 'Municipality']
df_muni.head()

,gwb_code_10,gwb_code_8,region,municipality,type_of_area,gwb_code,ind_wbi,a_inw,a_man,a_vrouw,...,g_afs_kv,g_afs_sc,g_3km_sc,a_opp_ha,a_lan_ha,a_wat_ha,pst_mvp,pst_dekp,ste_mvs,ste_oad
1,GM0003,3,Appingedam,Appingedam,Municipality,GM0003,.,11971,5802,6169,...,.,.,.,2458,2378,80,.,.,3,1045
9,GM0005,5,Bedum,Bedum,Municipality,GM0005,.,10479,5241,5238,...,.,.,.,4496,4454,41,.,.,4,678
19,GM0007,7,Bellingwedde,Bellingwedde,Municipality,GM0007,.,8919,4534,4385,...,.,.,.,11009,10837,172,.,.,5,151
45,GM0009,9,Ten Boer,Ten Boer,Municipality,GM0009,.,7288,3607,3681,...,.,.,.,4573,4531,42,.,.,5,371
60,GM0010,10,Delfzijl,Delfzijl,Municipality,GM0010,.,24965,12560,12405,...,.,.,.,22750,13313,9437,.,.,4,680

In [30]:
# Slicing data set by a particular municipality
hague_df = df_2017.loc[df_2017['municipality'] == 's-Gravenhage']
hague_df.head()

,gwb_code_10,gwb_code_8,region,municipality,type_of_area,gwb_code,ind_wbi,a_inw,a_man,a_vrouw,...,g_afs_kv,g_afs_sc,g_3km_sc,a_opp_ha,a_lan_ha,a_wat_ha,pst_mvp,pst_dekp,ste_mvs,ste_oad
8040,GM0518,518,'s-Gravenhage,s-Gravenhage,Municipality,GM0518,.,524882,259837,265045,...,.,.,.,9813,8269,1544,.,.,1,4834
8041,WK051801,51801,District 01 Oostduinen,s-Gravenhage,District,WK051801,1,0,0,0,...,.,.,.,318,308,10,.,.,4,681
8042,BU05180170,5180170,Oostduinen,s-Gravenhage,Neighborhood,BU05180170,1,0,0,0,...,.,.,.,318,308,10,2597,4,4,681
8043,WK051802,51802,District 02 Belgisch Park,s-Gravenhage,District,WK051802,1,8145,4025,4120,...,.,.,.,102,102,0,.,.,2,2438
8044,BU05180271,5180271,Belgisch Park,s-Gravenhage,Neighborhood,BU05180271,1,8145,4025,4120,...,.,.,.,102,102,0,2587,2,2,2438

In [36]:
crimes = pd.read_excel('C:/Users/ÐœÐ¸Ñ…Ð°Ð¸Ð»/AnacondaProjects/Advanced System Dynamics/Crimes.xlsx')
list_to_plot = crimes['Number'].values.tolist()
list_to_plot

[38,
 365,
 129,
 519,
 295,
 61,
 1309,
 195,
 646,
 94,
 372,
 665,
 302,
 209,
 241,
 241,
 1084,
 872,
 447,
 1095,
 938,
 826,
 97,
 86,
 613,
 1583,
 1447,
 5361,
 27,
 1632,
 1224,
 811,
 1547,
 1548,
 190,
 1365,
 352,
 3017,
 252,
 758,
 90,
 879,
 151,
 585]

In [31]:
# Getting interesting criterion to plot
slice_to_plot = hague_df.loc[hague_df['type_of_area'] == 'District']
# list_to_plot = slice_to_plot['a_inw'].values.tolist()

In [32]:
# An example of slicing data by a particular criteria
hague_sliced = hague_df[['region','a_man', 'a_vrouw', 'a_00_14', 'a_15_24', 'a_45_64', 'a_65_oo', 'a_marok', 'a_suri', 'a_tur']]
hague_sliced.head()

,region,a_man,a_vrouw,a_00_14,a_15_24,a_45_64,a_65_oo,a_marok,a_suri,a_tur
8040,'s-Gravenhage,259837,265045,92027,63856,134634,74675,30869,46413,39520
8041,District 01 Oostduinen,0,0,0,0,0,0,0,0,0
8042,Oostduinen,0,0,0,0,0,0,0,0,0
8043,District 02 Belgisch Park,4025,4120,1225,1195,2300,1640,70,145,40
8044,Belgisch Park,4025,4120,1225,1195,2300,1640,70,145,40

### Getting shapefiles to plot districts

In [33]:
import shapefile
sh = shapefile.Reader('C:/Users/ÐœÐ¸Ñ…Ð°Ð¸Ð»/AnacondaProjects/Disinofrmation project/Wijkgrenzen_Den_Haag/Wijkgrenzen_Den_Haag')

In [34]:
# Processing shapefiles
# Gettign shapefile records 
sh_recs = sh.records()

# Lists of the names to store particular values
district_names = list()

# Getting the names
for i in range(len(sh_recs)):
    district_names.append(sh_recs[i][2])

# Get the circle coordinates as example
district_coors = [s.points for s in sh.shapes()]
test_lon = np.empty(len(district_coors[0]))
test_lat = np.empty(len(district_coors[0]))

lons_combined = np.empty((44, 0)).tolist()
lats_combined = np.empty((44, 0)).tolist() 
for i in range(len(district_coors)):
    for j in range(len(district_coors[i])):
        lons_combined[i].append(district_coors[i][j][0])
        lats_combined[i].append(district_coors[i][j][1])

### Plotting interesting data

In [37]:
from bokeh.io import show
from bokeh.models import (ColumnDataSource, HoverTool, LogColorMapper, LinearColorMapper)
from bokeh.palettes import Viridis6 as palette
from bokeh.plotting import figure

palette = ['#CC3300', '#CF3C09',  '#D14411',  '#D44D1A',  '#D65523', '#D95E2B', '#DB6634',  
          '#DE6F3D',  '#E07745',  '#E3804E',  '#E68856',  '#E8915F', '#EB9A68',  '#EDA270', 
          '#F0AB79',  '#F2B382',  '#F5BC8A',  '#F7C493',  '#FACD9C',  '#FCD5A4',  '#FFDEAD']

palette.reverse()

color_mapper = LinearColorMapper(palette=palette)

source = ColumnDataSource(data=dict(
    x = lons_combined,
    y = lats_combined,
    name = district_names,
    population = list_to_plot,
))

TOOLS = "pan, wheel_zoom, reset, hover, save"

p = figure(
    title = "Den Haag, population per district", tools = TOOLS,
    x_axis_location = None, y_axis_location = None
)

p.grid.grid_line_color = None

p.patches('x', 'y', source=source,
          fill_color={'field': 'population', 'transform': color_mapper},
          fill_alpha=0.9, line_color="white", line_width=0.5)

hover = p.select_one(HoverTool)
hover.point_policy = "follow_mouse"
hover.tooltips = [
    ("Name", "@name"),
    ("Person in district", "@population")
#     ("(Long, Lat)", "($x, $y)"),
]

show(p)

In [10]:
# callback = CustomJS(code="""
# if (IPython.notebook.kernel !== undefined) {
#     var kernel = IPython.notebook.kernel;
#     cmd = "update_plot(" + cb_obj.value + ")";
#     kernel.execute(cmd, {}, {});
# }
# """)